appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kbV3slMAPQvkf5fitm2eYhiWyqE0EobrWuqs/jh5j1smWBsfbUqj9fKVOfs2C9jh0I/93bpvzEWLNDNTRmyQjBRCsSskNLg4gTSX8174cvd5EXl6JUqbKJU6LnIFDhR8H9MBJrofNZ8RBDhkYD0k/UxM1zmPe6Nx/pM1rVF+aFzD9lyFCGCZGVeNZRBEYvfsjEe2AHzf51aYQhX0t1qmFmqzJiGCuQJKTU/ddWaEKeBVmZnDmTqNINgTXygfBNm0qe9jbxV+M6scw2dIdzGwERojy2L1GpsfiI0aQXM0/4/jhFh6t1KEF55MSdXLE6/fLr4HTY82I9xATNe4yG09r3Yj5Ap+rsS1aG9JOL0ThcOyktFuqFTLDdwuRTU+SeG05RRRNo4yFKR34YeQKsfDez48kDMtBd8RUPlFoqGkGXlI3kJiIW7aa4lIBKwSPbpKMS2abi7sZevv8Qrx3cKllp9EJuyhJeiekQ013tlWUtAaGGCcyR3P/Nx8Fk8sjsdK7aiVOz3g5k/Ni+maAnqE/crCtN5jtr64rQIcpgLMkNZa6KtgWux6GzvxyAiquDG0AZ/PqJbtXWAfCUXiLd+TBCVYSg1AQsNdTgcxnYmRDcARyMkUsarOM/moV8zXBHXF0HGZzjov4CUwtCtacpig+IyIioroUkHaUFrq7qxtWMs=}
provider:
  win: azure
